//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALinq.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ALinq {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ALinq() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALinq.Resources.ALinq", typeof(ALinq).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; has no identity key 的本地化字符串。
        /// </summary>
        internal static string ArgumentTypeHasNoIdentityKey {
            get {
                return ResourceManager.GetString("ArgumentTypeHasNoIdentityKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot add change conflicts. They are added automatically during SubmitChanges. 的本地化字符串。
        /// </summary>
        internal static string CannotAddChangeConflicts {
            get {
                return ResourceManager.GetString("CannotAddChangeConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An attempt has been made to Attach or Add an entity that is not new, perhaps having been loaded from another DataContext.  This is not supported. 的本地化字符串。
        /// </summary>
        internal static string CannotAttachAddNonNewEntities {
            get {
                return ResourceManager.GetString("CannotAttachAddNonNewEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot attach an entity that already exists. 的本地化字符串。
        /// </summary>
        internal static string CannotAttachAlreadyExistingEntity {
            get {
                return ResourceManager.GetString("CannotAttachAlreadyExistingEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An entity can only be attached as modified without original state if it declares a version member or does not have an update check policy. 的本地化字符串。
        /// </summary>
        internal static string CannotAttachAsModifiedWithoutOriginalState {
            get {
                return ResourceManager.GetString("CannotAttachAsModifiedWithoutOriginalState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not allowed: Inheritance discriminator change from &apos;{0}&apos; to &apos;{1}&apos; would change type from &apos;{2}&apos; to &apos;{3}&apos;. 的本地化字符串。
        /// </summary>
        internal static string CannotChangeInheritanceType {
            get {
                return ResourceManager.GetString("CannotChangeInheritanceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interface &apos;{0}&apos; cannot contains method &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string CannotContainsMethod {
            get {
                return ResourceManager.GetString("CannotContainsMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interface &apos;{0}&apos; cannot contains property &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string CannotContainsProperty {
            get {
                return ResourceManager.GetString("CannotContainsProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t perform Create, Update or Delete operations on &apos;{0}&apos; because it has no primary key. 的本地化字符串。
        /// </summary>
        internal static string CannotPerformCUDOnReadOnlyTable {
            get {
                return ResourceManager.GetString("CannotPerformCUDOnReadOnlyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The operation cannot be performed during a call to SubmitChanges. 的本地化字符串。
        /// </summary>
        internal static string CannotPerformOperationDuringSubmitChanges {
            get {
                return ResourceManager.GetString("CannotPerformOperationDuringSubmitChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The operation cannot be performed for the entity because it is not being change tracked. 的本地化字符串。
        /// </summary>
        internal static string CannotPerformOperationForUntrackedObject {
            get {
                return ResourceManager.GetString("CannotPerformOperationForUntrackedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The operation can only be performed inside a user override method during a call to SubmitChanges. 的本地化字符串。
        /// </summary>
        internal static string CannotPerformOperationOutsideSubmitChanges {
            get {
                return ResourceManager.GetString("CannotPerformOperationOutsideSubmitChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot remove change conflicts.  的本地化字符串。
        /// </summary>
        internal static string CannotRemoveChangeConflicts {
            get {
                return ResourceManager.GetString("CannotRemoveChangeConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot remove an entity that has not been attached. 的本地化字符串。
        /// </summary>
        internal static string CannotRemoveUnattachedEntity {
            get {
                return ResourceManager.GetString("CannotRemoveUnattachedEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot add an entity that already exists. 的本地化字符串。
        /// </summary>
        internal static string CantAddAlreadyExistingItem {
            get {
                return ResourceManager.GetString("CantAddAlreadyExistingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot add an entity with a key that is already in use. 的本地化字符串。
        /// </summary>
        internal static string CantAddAlreadyExistingKey {
            get {
                return ResourceManager.GetString("CantAddAlreadyExistingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mapping Problem: The database column &apos;{0}&apos; is mapped more than once. 的本地化字符串。
        /// </summary>
        internal static string ColumnMappedMoreThanOnce {
            get {
                return ResourceManager.GetString("ColumnMappedMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item already exists in data context. 的本地化字符串。
        /// </summary>
        internal static string CouldNotAttach {
            get {
                return ResourceManager.GetString("CouldNotAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not convert from type &apos;{0}&apos; to type &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string CouldNotConvert {
            get {
                return ResourceManager.GetString("CouldNotConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not retrieve a Table for inheritance subtype &apos;{0}&apos;, try Table of {1} instead. 的本地化字符串。
        /// </summary>
        internal static string CouldNotGetTableForSubtype {
            get {
                return ResourceManager.GetString("CouldNotGetTableForSubtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An attempt was made to remove a relationship between a {0} and a {1}. However, one of the relationship&apos;s foreign keys ({2}) cannot be set to null. 的本地化字符串。
        /// </summary>
        internal static string CouldNotRemoveRelationshipBecauseOneSideCannotBeNull {
            get {
                return ResourceManager.GetString("CouldNotRemoveRelationshipBecauseOneSideCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A cycle was detected in the set of changes 的本地化字符串。
        /// </summary>
        internal static string CycleDetected {
            get {
                return ResourceManager.GetString("CycleDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The database generated a key that is already in use. 的本地化字符串。
        /// </summary>
        internal static string DatabaseGeneratedAlreadyExistingKey {
            get {
                return ResourceManager.GetString("DatabaseGeneratedAlreadyExistingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataContext accessed after Dispose. 的本地化字符串。
        /// </summary>
        internal static string DataContextCannotBeUsedAfterDispose {
            get {
                return ResourceManager.GetString("DataContextCannotBeUsedAfterDispose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value of member &apos;{0}&apos; of an object of type &apos;{1}&apos; changed.
        ///A member that is computed or generated by the database cannot be changed. 的本地化字符串。
        /// </summary>
        internal static string DbGeneratedChangeNotAllowed {
            get {
                return ResourceManager.GetString("DbGeneratedChangeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ADECRYPT 的本地化字符串。
        /// </summary>
        internal static string Decrypt {
            get {
                return ResourceManager.GetString("Decrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deferred loading requires that object tracking is also enabled. 的本地化字符串。
        /// </summary>
        internal static string DeferredLoadingRequiresObjectTracking {
            get {
                return ResourceManager.GetString("DeferredLoadingRequiresObjectTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --Callback into user code for delete. 的本地化字符串。
        /// </summary>
        internal static string DeleteCallbackComment {
            get {
                return ResourceManager.GetString("DeleteCallbackComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The entity is not of the correct type. 的本地化字符串。
        /// </summary>
        internal static string EntityIsTheWrongType {
            get {
                return ResourceManager.GetString("EntityIsTheWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The EntitySet is already loaded and the source cannot be changed. 的本地化字符串。
        /// </summary>
        internal static string EntitySetAlreadyLoaded {
            get {
                return ResourceManager.GetString("EntitySetAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot add an instance of an abstract class to EntitySet&lt;{0}&gt;. 的本地化字符串。
        /// </summary>
        internal static string EntitySetDataBindingWithAbstractBaseClass {
            get {
                return ResourceManager.GetString("EntitySetDataBindingWithAbstractBaseClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} must have a parameterless constructor when using IBindingList to add new instances. 的本地化字符串。
        /// </summary>
        internal static string EntitySetDataBindingWithNonPublicDefaultConstructor {
            get {
                return ResourceManager.GetString("EntitySetDataBindingWithNonPublicDefaultConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EntitySet was modified during enumeration. 的本地化字符串。
        /// </summary>
        internal static string EntitySetModifiedDuringEnumeration {
            get {
                return ResourceManager.GetString("EntitySetModifiedDuringEnumeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Argument {0} does not implement {1}. 的本地化字符串。
        /// </summary>
        internal static string ExpectedQueryableArgument {
            get {
                return ResourceManager.GetString("ExpectedQueryableArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected update, delete or change. 的本地化字符串。
        /// </summary>
        internal static string ExpectedUpdateDeleteOrChange {
            get {
                return ResourceManager.GetString("ExpectedUpdateDeleteOrChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value of member &apos;{0}&apos; of an object of type &apos;{1}&apos; changed.
        ///A member defining the identity of the object cannot be changed.
        ///Consider adding a new object with new identity and deleting the existing one instead. 的本地化字符串。
        /// </summary>
        internal static string IdentityChangeNotAllowed {
            get {
                return ResourceManager.GetString("IdentityChangeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cycles not allowed in LoadOptions LoadWith type graph. 的本地化字符串。
        /// </summary>
        internal static string IncludeCycleNotAllowed {
            get {
                return ResourceManager.GetString("IncludeCycleNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoadWith is not allowed after freeze or attach to DataContext. 的本地化字符串。
        /// </summary>
        internal static string IncludeNotAllowedAfterFreeze {
            get {
                return ResourceManager.GetString("IncludeNotAllowedAfterFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The member &apos;{0}&apos; was changed to be inconsistent with the association member &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string InconsistentAssociationAndKeyChange {
            get {
                return ResourceManager.GetString("InconsistentAssociationAndKeyChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Member AutoSync failure. For members to be Auto-Synced after insert, the type must either have an auto-generated identity, or a key that is not modified by the database after insert. 的本地化字符串。
        /// </summary>
        internal static string InsertAutoSyncFailure {
            get {
                return ResourceManager.GetString("InsertAutoSyncFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --Callback into user code for insert. 的本地化字符串。
        /// </summary>
        internal static string InsertCallbackComment {
            get {
                return ResourceManager.GetString("InsertCallbackComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The expression specified must be of the form p.A, where p is the parameter and A is a property or field member.  的本地化字符串。
        /// </summary>
        internal static string InvalidLoadOptionsLoadMemberSpecification {
            get {
                return ResourceManager.GetString("InvalidLoadOptionsLoadMemberSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key is the wrong size. Expected {0}. Actual {1}. 的本地化字符串。
        /// </summary>
        internal static string KeyIsWrongSize {
            get {
                return ResourceManager.GetString("KeyIsWrongSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key value is the wrong type. Expected assignable from {0}. Actual {1}. 的本地化字符串。
        /// </summary>
        internal static string KeyValueIsWrongType {
            get {
                return ResourceManager.GetString("KeyValueIsWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting load options is not allowed after results have been returned from a query. 的本地化字符串。
        /// </summary>
        internal static string LoadOptionsChangeNotAllowedAfterQuery {
            get {
                return ResourceManager.GetString("LoadOptionsChangeNotAllowedAfterQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not modify EntitySet. 的本地化字符串。
        /// </summary>
        internal static string ModifyDuringAddOrRemove {
            get {
                return ResourceManager.GetString("ModifyDuringAddOrRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid association mapping for member &apos;{0}.{1}&apos;.  &apos;{2}&apos; is not an entity. 的本地化字符串。
        /// </summary>
        internal static string NonEntityAssociationMapping {
            get {
                return ResourceManager.GetString("NonEntityAssociationMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current version could not run under Chinese Simplified Culture. 的本地化字符串。
        /// </summary>
        internal static string NotSupportCultrue {
            get {
                return ResourceManager.GetString("NotSupportCultrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Object tracking is not enabled for the current data context instance. 的本地化字符串。
        /// </summary>
        internal static string ObjectTrackingRequired {
            get {
                return ResourceManager.GetString("ObjectTrackingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data context options cannot be modified after results have been returned from a query. 的本地化字符串。
        /// </summary>
        internal static string OptionsCannotBeModifiedAfterQuery {
            get {
                return ResourceManager.GetString("OptionsCannotBeModifiedAfterQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The original state instance has the wrong type. 的本地化字符串。
        /// </summary>
        internal static string OriginalEntityIsWrongType {
            get {
                return ResourceManager.GetString("OriginalEntityIsWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ALinq 的本地化字符串。
        /// </summary>
        internal static string OwningTeam {
            get {
                return ResourceManager.GetString("OwningTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specified provider type &apos;{0}&apos; does not implement &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ProviderDoesNotImplementRequiredInterface {
            get {
                return ResourceManager.GetString("ProviderDoesNotImplementRequiredInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Non-null provider type expected. 的本地化字符串。
        /// </summary>
        internal static string ProviderTypeNull {
            get {
                return ResourceManager.GetString("ProviderTypeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to refresh the specified object.  The object no longer exists in the database. 的本地化字符串。
        /// </summary>
        internal static string RefreshOfDeletedObject {
            get {
                return ResourceManager.GetString("RefreshOfDeletedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row not found or changed. 的本地化字符串。
        /// </summary>
        internal static string RowNotFoundOrChanged {
            get {
                return ResourceManager.GetString("RowNotFoundOrChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The operator &apos;{0}&apos; is not supported in Subquery. 的本地化字符串。
        /// </summary>
        internal static string SubqueryDoesNotSupportOperator {
            get {
                return ResourceManager.GetString("SubqueryDoesNotSupportOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subquery must be a sequence expression. 的本地化字符串。
        /// </summary>
        internal static string SubqueryMustBeSequence {
            get {
                return ResourceManager.GetString("SubqueryMustBeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SetSubquery is not allowed after freeze or attach to DataContext. 的本地化字符串。
        /// </summary>
        internal static string SubqueryNotAllowedAfterFreeze {
            get {
                return ResourceManager.GetString("SubqueryNotAllowedAfterFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subquery is not supported on &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string SubqueryNotSupportedOn {
            get {
                return ResourceManager.GetString("SubqueryNotSupportedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subquery is not supported on &apos;{0}&apos; of type &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string SubqueryNotSupportedOnType {
            get {
                return ResourceManager.GetString("SubqueryNotSupportedOnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instance of type &apos;{0}&apos; could not be added. This type is not part of the mapped type system. 的本地化字符串。
        /// </summary>
        internal static string TypeCouldNotBeAdded {
            get {
                return ResourceManager.GetString("TypeCouldNotBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instance of type &apos;{0}&apos; could not be removed. This type is not part of the mapped type system. 的本地化字符串。
        /// </summary>
        internal static string TypeCouldNotBeRemoved {
            get {
                return ResourceManager.GetString("TypeCouldNotBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instance of type &apos;{0}&apos; could not be tracked. This type is not part of the mapped type system. 的本地化字符串。
        /// </summary>
        internal static string TypeCouldNotBeTracked {
            get {
                return ResourceManager.GetString("TypeCouldNotBeTracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; is not an entity. 的本地化字符串。
        /// </summary>
        internal static string TypeIsNotEntity {
            get {
                return ResourceManager.GetString("TypeIsNotEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; is not mapped as a Table. 的本地化字符串。
        /// </summary>
        internal static string TypeIsNotMarkedAsTable {
            get {
                return ResourceManager.GetString("TypeIsNotMarkedAsTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to determine DataContext for compiled query execution. 的本地化字符串。
        /// </summary>
        internal static string UnableToDetermineDataContext {
            get {
                return ResourceManager.GetString("UnableToDetermineDataContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unhandled Binding Type: {0} 的本地化字符串。
        /// </summary>
        internal static string UnhandledBindingType {
            get {
                return ResourceManager.GetString("UnhandledBindingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unhandled Expression Type: {0} 的本地化字符串。
        /// </summary>
        internal static string UnhandledExpressionType {
            get {
                return ResourceManager.GetString("UnhandledExpressionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An object specified for refresh is not recognized. 的本地化字符串。
        /// </summary>
        internal static string UnrecognizedRefreshObject {
            get {
                return ResourceManager.GetString("UnrecognizedRefreshObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --Callback into user code for update. 的本地化字符串。
        /// </summary>
        internal static string UpdateCallbackComment {
            get {
                return ResourceManager.GetString("UpdateCallbackComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} of {1} updates failed. 的本地化字符串。
        /// </summary>
        internal static string UpdatesFailedMessage {
            get {
                return ResourceManager.GetString("UpdatesFailedMessage", resourceCulture);
            }
        }
    }
}
