//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALinq.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ALinq_SqlClient {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ALinq_SqlClient() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALinq.Resources.ALinq.SqlClient", typeof(ALinq_SqlClient).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The string parameter &apos;{0}&apos; was expected to have length greater than zero. 的本地化字符串。
        /// </summary>
        internal static string ArgumentEmpty {
            get {
                return ResourceManager.GetString("ArgumentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One or more type mismatches in argument &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ArgumentTypeMismatch {
            get {
                return ResourceManager.GetString("ArgumentTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The argument &apos;{0}&apos; was the wrong type. Expected &apos;{1}&apos;. Actual &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ArgumentWrongType {
            get {
                return ResourceManager.GetString("ArgumentWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The argument &apos;{0}&apos; was the wrong value.  的本地化字符串。
        /// </summary>
        internal static string ArgumentWrongValue {
            get {
                return ResourceManager.GetString("ArgumentWrongValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A query parameter cannot be of type &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string BadParameterType {
            get {
                return ResourceManager.GetString("BadParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bad projection in Select. 的本地化字符串。
        /// </summary>
        internal static string BadProjectionInSelect {
            get {
                return ResourceManager.GetString("BadProjectionInSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Binary operator not recognized: {0} 的本地化字符串。
        /// </summary>
        internal static string BinaryOperatorNotRecognized {
            get {
                return ResourceManager.GetString("BinaryOperatorNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; is not supported in aggregation operations. 的本地化字符串。
        /// </summary>
        internal static string CannotAggregateType {
            get {
                return ResourceManager.GetString("CannotAggregateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The null value cannot be assigned to a member with type {0} which is a non-nullable value type. 的本地化字符串。
        /// </summary>
        internal static string CannotAssignNull {
            get {
                return ResourceManager.GetString("CannotAssignNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot assign value to member &apos;{0}&apos;. It does not define a setter. 的本地化字符串。
        /// </summary>
        internal static string CannotAssignToMember {
            get {
                return ResourceManager.GetString("CannotAssignToMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot compare entities associated with different tables. 的本地化字符串。
        /// </summary>
        internal static string CannotCompareItemsAssociatedWithDifferentTable {
            get {
                return ResourceManager.GetString("CannotCompareItemsAssociatedWithDifferentTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot convert type &apos;{0}&apos; to EntityRef/Link. 的本地化字符串。
        /// </summary>
        internal static string CannotConvertToEntityRef {
            get {
                return ResourceManager.GetString("CannotConvertToEntityRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot delete items of type {0}. 的本地化字符串。
        /// </summary>
        internal static string CannotDeleteTypesOf {
            get {
                return ResourceManager.GetString("CannotDeleteTypesOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The query results cannot be enumerated more than once. 的本地化字符串。
        /// </summary>
        internal static string CannotEnumerateResultsMoreThanOnce {
            get {
                return ResourceManager.GetString("CannotEnumerateResultsMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Explicit construction of entity type &apos;{0}&apos; in query is not allowed. 的本地化字符串。
        /// </summary>
        internal static string CannotMaterializeEntityType {
            get {
                return ResourceManager.GetString("CannotMaterializeEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot translate expression to SQL for this server version. 的本地化字符串。
        /// </summary>
        internal static string CannotTranslateExpressionToSql {
            get {
                return ResourceManager.GetString("CannotTranslateExpressionToSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local sequence cannot be used in LINQ to SQL implementation of query operators except the Contains() operator. 的本地化字符串。
        /// </summary>
        internal static string CapturedValuesCannotBeSequences {
            get {
                return ResourceManager.GetString("CapturedValuesCannotBeSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Class literals are not allowed: {0}. 的本地化字符串。
        /// </summary>
        internal static string ClassLiteralsNotAllowed {
            get {
                return ResourceManager.GetString("ClassLiteralsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client case should not hold &apos;{0}&apos;. It should probably have been SqlSimpleCase. 的本地化字符串。
        /// </summary>
        internal static string ClientCaseShouldNotHold {
            get {
                return ResourceManager.GetString("ClientCaseShouldNotHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected Node with CLR Type of &apos;bool&apos; to have SQL type of &apos;Bit&apos; or &apos;Predicate&apos;. Instead, it was type &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ClrBoolDoesNotAgreeWithSqlType {
            get {
                return ResourceManager.GetString("ClrBoolDoesNotAgreeWithSqlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column cannot refer to itself. 的本地化字符串。
        /// </summary>
        internal static string ColumnCannotReferToItself {
            get {
                return ResourceManager.GetString("ColumnCannotReferToItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column&apos;s ClrType did not agree with its Expression&apos;s ClrType. 的本地化字符串。
        /// </summary>
        internal static string ColumnClrTypeDoesNotAgreeWithExpressionsClrType {
            get {
                return ResourceManager.GetString("ColumnClrTypeDoesNotAgreeWithExpressionsClrType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column &apos;{0}&apos; is defined in multiple places. 的本地化字符串。
        /// </summary>
        internal static string ColumnIsDefinedInMultiplePlaces {
            get {
                return ResourceManager.GetString("ColumnIsDefinedInMultiplePlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column &apos;{0}&apos; is not accessible through &apos;distinct&apos;. 的本地化字符串。
        /// </summary>
        internal static string ColumnIsNotAccessibleThroughDistinct {
            get {
                return ResourceManager.GetString("ColumnIsNotAccessibleThroughDistinct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column &apos;{0}&apos; is not accessible through group-by. 的本地化字符串。
        /// </summary>
        internal static string ColumnIsNotAccessibleThroughGroupBy {
            get {
                return ResourceManager.GetString("ColumnIsNotAccessibleThroughGroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column referenced is not in scope: &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ColumnReferencedIsNotInScope {
            get {
                return ResourceManager.GetString("ColumnReferencedIsNotInScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comparison operators not supported for type &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ComparisonNotSupportedForType {
            get {
                return ResourceManager.GetString("ComparisonNotSupportedForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compiled queries across DataContexts with different LoadOptions not supported. 的本地化字符串。
        /// </summary>
        internal static string CompiledQueryAgainstMultipleShapesNotSupported {
            get {
                return ResourceManager.GetString("CompiledQueryAgainstMultipleShapesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A compiled query cannot return type &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string CompiledQueryCannotReturnType {
            get {
                return ResourceManager.GetString("CompiledQueryCannotReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constructed arrays are only supported for &apos;Contains&apos;. 的本地化字符串。
        /// </summary>
        internal static string ConstructedArraysNotSupported {
            get {
                return ResourceManager.GetString("ConstructedArraysNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SqlContext is not initialized. 的本地化字符串。
        /// </summary>
        internal static string ContextNotInitialized {
            get {
                return ResourceManager.GetString("ContextNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no supported conversion from a Boolean to a Character type. 的本地化字符串。
        /// </summary>
        internal static string ConvertToCharFromBoolNotSupported {
            get {
                return ResourceManager.GetString("ConvertToCharFromBoolNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only DateTimes or strings can be converted to DateTime. 的本地化字符串。
        /// </summary>
        internal static string ConvertToDateTimeOnlyForDateTimeOrString {
            get {
                return ResourceManager.GetString("ConvertToDateTimeOnlyForDateTimeOrString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not assign sequence of {0} to type {1}. 的本地化字符串。
        /// </summary>
        internal static string CouldNotAssignSequence {
            get {
                return ResourceManager.GetString("CouldNotAssignSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MemberInfo &apos;{0}&apos; had no corresponding field or property. 的本地化字符串。
        /// </summary>
        internal static string CouldNotConvertToPropertyOrField {
            get {
                return ResourceManager.GetString("CouldNotConvertToPropertyOrField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to determine catalog name. 的本地化字符串。
        /// </summary>
        internal static string CouldNotDetermineCatalogName {
            get {
                return ResourceManager.GetString("CouldNotDetermineCatalogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to determine SQL type for &apos;{0}&apos; that can also be generated by the server. 的本地化字符串。
        /// </summary>
        internal static string CouldNotDetermineDbGeneratedSqlType {
            get {
                return ResourceManager.GetString("CouldNotDetermineDbGeneratedSqlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to determine SQL type for &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string CouldNotDetermineSqlType {
            get {
                return ResourceManager.GetString("CouldNotDetermineSqlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not get the ClrType. 的本地化字符串。
        /// </summary>
        internal static string CouldNotGetClrType {
            get {
                return ResourceManager.GetString("CouldNotGetClrType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not get the SqlType. 的本地化字符串。
        /// </summary>
        internal static string CouldNotGetSqlType {
            get {
                return ResourceManager.GetString("CouldNotGetSqlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not handle alias ref of {0}. 的本地化字符串。
        /// </summary>
        internal static string CouldNotHandleAliasRef {
            get {
                return ResourceManager.GetString("CouldNotHandleAliasRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not translate expression &apos;{0}&apos; into SQL and could not treat it as a local expression. 的本地化字符串。
        /// </summary>
        internal static string CouldNotTranslateExpressionForReading {
            get {
                return ResourceManager.GetString("CouldNotTranslateExpressionForReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to create database because mapped class &apos;{0}&apos; has zero members. 的本地化字符串。
        /// </summary>
        internal static string CreateDatabaseFailedBecauseOfClassWithNoMembers {
            get {
                return ResourceManager.GetString("CreateDatabaseFailedBecauseOfClassWithNoMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to create database because data context &apos;{0}&apos; has no tables. 的本地化字符串。
        /// </summary>
        internal static string CreateDatabaseFailedBecauseOfContextWithNoTables {
            get {
                return ResourceManager.GetString("CreateDatabaseFailedBecauseOfContextWithNoTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to create database because the database &apos;{0}&apos; already exists. 的本地化字符串。
        /// </summary>
        internal static string CreateDatabaseFailedBecauseSqlCEDatabaseAlreadyExists {
            get {
                return ResourceManager.GetString("CreateDatabaseFailedBecauseSqlCEDatabaseAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation not allowed after DeleteDatabase call. 的本地化字符串。
        /// </summary>
        internal static string DatabaseDeleteThroughContext {
            get {
                return ResourceManager.GetString("DatabaseDeleteThroughContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deferred member not one of EntitySet, EntityRef or Link. 的本地化字符串。
        /// </summary>
        internal static string DeferredMemberWrongType {
            get {
                return ResourceManager.GetString("DeferredMemberWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Did not expect &apos;as&apos; operator in &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string DidNotExpectAs {
            get {
                return ResourceManager.GetString("DidNotExpectAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Did not expect type binding back. This should result in a type case not a simple case. 的本地化字符串。
        /// </summary>
        internal static string DidNotExpectTypeBinding {
            get {
                return ResourceManager.GetString("DidNotExpectTypeBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Did not expect operation to change result type. Original type was &apos;{0}&apos; new type is &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string DidNotExpectTypeChange {
            get {
                return ResourceManager.GetString("DidNotExpectTypeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Distributed transactions are not allowed. 的本地化字符串。
        /// </summary>
        internal static string DistributedTransactionsAreNotAllowed {
            get {
                return ResourceManager.GetString("DistributedTransactionsAreNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty case is not supported. 的本地化字符串。
        /// </summary>
        internal static string EmptyCaseNotSupported {
            get {
                return ResourceManager.GetString("EmptyCaseNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;Except&apos; is not supported for hierarchical result types. 的本地化字符串。
        /// </summary>
        internal static string ExceptNotSupportedForHierarchicalTypes {
            get {
                return ResourceManager.GetString("ExceptNotSupportedForHierarchicalTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected a &apos;Bit&apos; here but found a &apos;Predicate&apos;. 的本地化字符串。
        /// </summary>
        internal static string ExpectedBitFoundPredicate {
            get {
                return ResourceManager.GetString("ExpectedBitFoundPredicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected Clr Types to agree. One was &apos;{0}&apos; the other was &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ExpectedClrTypesToAgree {
            get {
                return ResourceManager.GetString("ExpectedClrTypesToAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected no ObjectType nodes to remain. 的本地化字符串。
        /// </summary>
        internal static string ExpectedNoObjectType {
            get {
                return ResourceManager.GetString("ExpectedNoObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected a &apos;Predicate&apos; here but found a &apos;Bit&apos;. 的本地化字符串。
        /// </summary>
        internal static string ExpectedPredicateFoundBit {
            get {
                return ResourceManager.GetString("ExpectedPredicateFoundBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected type &apos;{0}&apos; of argument &apos;{1}&apos; to implement IQueryable of &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ExpectedQueryableArgument {
            get {
                return ResourceManager.GetString("ExpectedQueryableArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expression is not a deferred query source. 的本地化字符串。
        /// </summary>
        internal static string ExpressionNotDeferredQuerySource {
            get {
                return ResourceManager.GetString("ExpressionNotDeferredQuerySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General collection materialization is not supported. 的本地化字符串。
        /// </summary>
        internal static string GeneralCollectionMaterializationNotSupported {
            get {
                return ResourceManager.GetString("GeneralCollectionMaterializationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A grouping cannot be used as an order criterion; you may want to use its key instead. 的本地化字符串。
        /// </summary>
        internal static string GroupingNotSupportedAsOrderCriterion {
            get {
                return ResourceManager.GetString("GroupingNotSupportedAsOrderCriterion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The IIF method returns two separate types: {0}, {1}.  Translation to SQL does not support different return types. 的本地化字符串。
        /// </summary>
        internal static string IifReturnTypesMustBeEqual {
            get {
                return ResourceManager.GetString("IifReturnTypesMustBeEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Should not have reached this point. 的本地化字符串。
        /// </summary>
        internal static string Impossible {
            get {
                return ResourceManager.GetString("Impossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The translation of String.IndexOf to SQL does not support versions with a StringComparison argument. 的本地化字符串。
        /// </summary>
        internal static string IndexOfWithStringComparisonArgNotSupported {
            get {
                return ResourceManager.GetString("IndexOfWithStringComparisonArgNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Descent limit exceeded. 的本地化字符串。
        /// </summary>
        internal static string InfiniteDescent {
            get {
                return ResourceManager.GetString("InfiniteDescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The item of an insert must be a constant value expression. 的本地化字符串。
        /// </summary>
        internal static string InsertItemMustBeConstant {
            get {
                return ResourceManager.GetString("InsertItemMustBeConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;Intersect&apos; is not supported for hierarchical result types. 的本地化字符串。
        /// </summary>
        internal static string IntersectNotSupportedForHierarchicalTypes {
            get {
                return ResourceManager.GetString("IntersectNotSupportedForHierarchicalTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; must be string, or DbConnection. 的本地化字符串。
        /// </summary>
        internal static string InvalidConnectionArgument {
            get {
                return ResourceManager.GetString("InvalidConnectionArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The primary key column of type &apos;{0}&apos; cannot be generated by the server.  的本地化字符串。
        /// </summary>
        internal static string InvalidDbGeneratedType {
            get {
                return ResourceManager.GetString("InvalidDbGeneratedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not format node &apos;{0}&apos; for execution as SQL. 的本地化字符串。
        /// </summary>
        internal static string InvalidFormatNode {
            get {
                return ResourceManager.GetString("InvalidFormatNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The group by operation contains an expression that cannot be translated. 的本地化字符串。
        /// </summary>
        internal static string InvalidGroupByExpression {
            get {
                return ResourceManager.GetString("InvalidGroupByExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A group by expression can only contain non-constant scalars that are comparable by the server. The expression with type &apos;{0}&apos; is not comparable. 的本地化字符串。
        /// </summary>
        internal static string InvalidGroupByExpressionType {
            get {
                return ResourceManager.GetString("InvalidGroupByExpressionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The method &apos;{0}&apos; is not mapped as a stored procedure or user-defined function. 的本地化字符串。
        /// </summary>
        internal static string InvalidMethodExecution {
            get {
                return ResourceManager.GetString("InvalidMethodExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An order by expression can only contain non-constant scalars that are order comparable by the server. The expression with type &apos;{0}&apos; is not order comparable. 的本地化字符串。
        /// </summary>
        internal static string InvalidOrderByExpression {
            get {
                return ResourceManager.GetString("InvalidOrderByExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified type &apos;{0}&apos; is not a valid provider type. 的本地化字符串。
        /// </summary>
        internal static string InvalidProviderType {
            get {
                return ResourceManager.GetString("InvalidProviderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reference to removed alias discovered during deflation. 的本地化字符串。
        /// </summary>
        internal static string InvalidReferenceToRemovedAliasDuringDeflation {
            get {
                return ResourceManager.GetString("InvalidReferenceToRemovedAliasDuringDeflation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; is not a valid return type for a mapped stored procedure method. 的本地化字符串。
        /// </summary>
        internal static string InvalidReturnFromSproc {
            get {
                return ResourceManager.GetString("InvalidReturnFromSproc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sequence operator call is only valid for Sequence, Queryable or DataQueryExtensions not for &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string InvalidSequenceOperatorCall {
            get {
                return ResourceManager.GetString("InvalidSequenceOperatorCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The translation of String.LastIndexOf to SQL does not support versions with a StringComparison argument. 的本地化字符串。
        /// </summary>
        internal static string LastIndexOfWithStringComparisonArgNotSupported {
            get {
                return ResourceManager.GetString("LastIndexOfWithStringComparisonArgNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translation would contain LEN of Text or NText arguments: {0} 的本地化字符串。
        /// </summary>
        internal static string LenOfTextOrNTextNotSupported {
            get {
                return ResourceManager.GetString("LenOfTextOrNTextNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attempting to delete the database &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string LogAttemptingToDeleteDatabase {
            get {
                return ResourceManager.GetString("LogAttemptingToDeleteDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: {1}. 的本地化字符串。
        /// </summary>
        internal static string LogGeneralInfoMessage {
            get {
                return ResourceManager.GetString("LogGeneralInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execute stored procedure: {0}({1}). 的本地化字符串。
        /// </summary>
        internal static string LogStoredProcedureExecution {
            get {
                return ResourceManager.GetString("LogStoredProcedureExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; must declare a default (parameterless) constructor in order to be constructed during mapping. 的本地化字符串。
        /// </summary>
        internal static string MappedTypeMustHaveDefaultConstructor {
            get {
                return ResourceManager.GetString("MappedTypeMustHaveDefaultConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For translation to SQL, the Math.Round method needs a MidpointRounding parameter. Use &apos;AwayFromZero&apos; to specify the SQL function ROUND. 的本地化字符串。
        /// </summary>
        internal static string MathRoundNotSupported {
            get {
                return ResourceManager.GetString("MathRoundNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translation would contain an out parameter of type Text, NText or Image: {0} 的本地化字符串。
        /// </summary>
        internal static string MaxSizeNotSupported {
            get {
                return ResourceManager.GetString("MaxSizeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Member access &apos;{0}&apos; of &apos;{1}&apos; not legal on type &apos;{2}. 的本地化字符串。
        /// </summary>
        internal static string MemberAccessIllegal {
            get {
                return ResourceManager.GetString("MemberAccessIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The member &apos;{0}.{1}&apos; has no supported translation to SQL. 的本地化字符串。
        /// </summary>
        internal static string MemberCannotBeTranslated {
            get {
                return ResourceManager.GetString("MemberCannotBeTranslated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Member &apos;{0}.{1}&apos; could not be translated. 的本地化字符串。
        /// </summary>
        internal static string MemberCouldNotBeTranslated {
            get {
                return ResourceManager.GetString("MemberCouldNotBeTranslated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Binding error: Member &apos;{0}.{1}&apos; not found in projection. 的本地化字符串。
        /// </summary>
        internal static string MemberNotPartOfProjection {
            get {
                return ResourceManager.GetString("MemberNotPartOfProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The method &apos;{0}&apos; has a translation to SQL, but the overload &apos;{1}&apos; does not. 的本地化字符串。
        /// </summary>
        internal static string MethodFormHasNoSupportConversionToSql {
            get {
                return ResourceManager.GetString("MethodFormHasNoSupportConversionToSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method &apos;{0}&apos; has no supported translation to SQL. 的本地化字符串。
        /// </summary>
        internal static string MethodHasNoSupportConversionToSql {
            get {
                return ResourceManager.GetString("MethodHasNoSupportConversionToSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The method specified ({0}) is not mapped to a stored procedure. 的本地化字符串。
        /// </summary>
        internal static string MethodNotMappedToStoredProcedure {
            get {
                return ResourceManager.GetString("MethodNotMappedToStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No method in type &apos;{0}&apos; matching arguments. 的本地化字符串。
        /// </summary>
        internal static string NoMethodInTypeMatchingArguments {
            get {
                return ResourceManager.GetString("NoMethodInTypeMatchingArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only arguments that can be evaluated on the client are supported for the {0} method. 的本地化字符串。
        /// </summary>
        internal static string NonConstantExpressionsNotSupportedFor {
            get {
                return ResourceManager.GetString("NonConstantExpressionsNotSupportedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only arguments that can be evaluated on the client are supported for the MidpointRounding argument in Math.Round. 的本地化字符串。
        /// </summary>
        internal static string NonConstantExpressionsNotSupportedForRounding {
            get {
                return ResourceManager.GetString("NonConstantExpressionsNotSupportedForRounding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameterless aggregate operator &apos;{0}&apos; is not supported over projections. 的本地化字符串。
        /// </summary>
        internal static string NonCountAggregateFunctionsAreNotValidOnProjections {
            get {
                return ResourceManager.GetString("NonCountAggregateFunctionsAreNotValidOnProjections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ALinq 的本地化字符串。
        /// </summary>
        internal static string OwningTeam {
            get {
                return ResourceManager.GetString("OwningTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameter &apos;{0}&apos; is not in scope. 的本地化字符串。
        /// </summary>
        internal static string ParameterNotInScope {
            get {
                return ResourceManager.GetString("ParameterNotInScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameters cannot be sequences. 的本地化字符串。
        /// </summary>
        internal static string ParametersCannotBeSequences {
            get {
                return ResourceManager.GetString("ParametersCannotBeSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Provider cannot be accessed after Dispose. 的本地化字符串。
        /// </summary>
        internal static string ProviderCannotBeUsedAfterDispose {
            get {
                return ResourceManager.GetString("ProviderCannotBeUsedAfterDispose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot open &apos;{0}&apos;. Provider &apos;{1}&apos; not installed. 的本地化字符串。
        /// </summary>
        internal static string ProviderNotInstalled {
            get {
                return ResourceManager.GetString("ProviderNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Queries with local collections are not supported 的本地化字符串。
        /// </summary>
        internal static string QueryOnLocalCollectionNotSupported {
            get {
                return ResourceManager.GetString("QueryOnLocalCollectionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The query operator &apos;{0}&apos; is not supported. 的本地化字符串。
        /// </summary>
        internal static string QueryOperatorNotSupported {
            get {
                return ResourceManager.GetString("QueryOperatorNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported overload used for query operator &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string QueryOperatorOverloadNotSupported {
            get {
                return ResourceManager.GetString("QueryOperatorOverloadNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reader used after dispose. 的本地化字符串。
        /// </summary>
        internal static string ReaderUsedAfterDispose {
            get {
                return ResourceManager.GetString("ReaderUsedAfterDispose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The required column &apos;{0}&apos; does not exist in the results. 的本地化字符串。
        /// </summary>
        internal static string RequiredColumnDoesNotExist {
            get {
                return ResourceManager.GetString("RequiredColumnDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result type &apos;{0}&apos; is not mapped to function &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ResultTypeNotMappedToFunction {
            get {
                return ResourceManager.GetString("ResultTypeNotMappedToFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SelectMany does not support strings. 的本地化字符串。
        /// </summary>
        internal static string SelectManyDoesNotSupportStrings {
            get {
                return ResourceManager.GetString("SelectManyDoesNotSupportStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sequence operators not supported for type &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string SequenceOperatorsNotSupportedForType {
            get {
                return ResourceManager.GetString("SequenceOperatorsNotSupportedForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simple case should not hold &apos;{0}&apos; should probably have been SqlClientCase. 的本地化字符串。
        /// </summary>
        internal static string SimpleCaseShouldNotHold {
            get {
                return ResourceManager.GetString("SimpleCaseShouldNotHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Skip() operator is valid only over ordered queries. 的本地化字符串。
        /// </summary>
        internal static string SkipIsValidOnlyOverOrderedQueries {
            get {
                return ResourceManager.GetString("SkipIsValidOnlyOverOrderedQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Skip operator is not supported for sequences containing sequences (with the exception of IGrouping under SQL Server 2005). 的本地化字符串。
        /// </summary>
        internal static string SkipNotSupportedForSequenceTypes {
            get {
                return ResourceManager.GetString("SkipNotSupportedForSequenceTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This provider supports Skip() only over ordered queries returning entities or projections that contain all identity columns, where the query is a single-table (non-join) query, or is a Distinct, Except, Intersect, or Union (not Concat) operation. 的本地化字符串。
        /// </summary>
        internal static string SkipRequiresSingleTableQueryWithPKs {
            get {
                return ResourceManager.GetString("SkipRequiresSingleTableQueryWithPKs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source Expression: {0} 的本地化字符串。
        /// </summary>
        internal static string SourceExpressionAnnotation {
            get {
                return ResourceManager.GetString("SourceExpressionAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stored Procedures cannot be used inside queries. 的本地化字符串。
        /// </summary>
        internal static string SprocsCannotBeComposed {
            get {
                return ResourceManager.GetString("SprocsCannotBeComposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method &apos;{0}&apos; cannot be used on the client; it is only for translation to SQL. 的本地化字符串。
        /// </summary>
        internal static string SqlMethodOnlyForSql {
            get {
                return ResourceManager.GetString("SqlMethodOnlyForSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translation would contain an expression of type Text, NText or Image in a SELECT DISTINCT clause: {0} 的本地化字符串。
        /// </summary>
        internal static string TextNTextAndImageCannotOccurInDistinct {
            get {
                return ResourceManager.GetString("TextNTextAndImageCannotOccurInDistinct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translation would contain an expression of type Text, NText or Image in a SELECT within a UNION: {0} 的本地化字符串。
        /// </summary>
        internal static string TextNTextAndImageCannotOccurInUnion {
            get {
                return ResourceManager.GetString("TextNTextAndImageCannotOccurInUnion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method ToString can only be translated to SQL for primitive types. 的本地化字符串。
        /// </summary>
        internal static string ToStringOnlySupportedForPrimitiveTypes {
            get {
                return ResourceManager.GetString("ToStringOnlySupportedForPrimitiveTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transaction does not match connection. 的本地化字符串。
        /// </summary>
        internal static string TransactionDoesNotMatchConnection {
            get {
                return ResourceManager.GetString("TransactionDoesNotMatchConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type Binary operator not recognized. 的本地化字符串。
        /// </summary>
        internal static string TypeBinaryOperatorNotRecognized {
            get {
                return ResourceManager.GetString("TypeBinaryOperatorNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot order by type &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string TypeCannotBeOrdered {
            get {
                return ResourceManager.GetString("TypeCannotBeOrdered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type column with unhandled source 的本地化字符串。
        /// </summary>
        internal static string TypeColumnWithUnhandledSource {
            get {
                return ResourceManager.GetString("TypeColumnWithUnhandledSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Binding error: Member &apos;{0}.{1}&apos; is not a mapped member of &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string UnableToBindUnmappedMember {
            get {
                return ResourceManager.GetString("UnableToBindUnmappedMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column declaration found outside row or table declaration. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedFloatingColumn {
            get {
                return ResourceManager.GetString("UnexpectedFloatingColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected node: {0} 的本地化字符串。
        /// </summary>
        internal static string UnexpectedNode {
            get {
                return ResourceManager.GetString("UnexpectedNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected shared-expression found. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedSharedExpression {
            get {
                return ResourceManager.GetString("UnexpectedSharedExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected shared-expression reference found. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedSharedExpressionReference {
            get {
                return ResourceManager.GetString("UnexpectedSharedExpressionReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected type code: {0} 的本地化字符串。
        /// </summary>
        internal static string UnexpectedTypeCode {
            get {
                return ResourceManager.GetString("UnexpectedTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unhandled binding type: {0} 的本地化字符串。
        /// </summary>
        internal static string UnhandledBindingType {
            get {
                return ResourceManager.GetString("UnhandledBindingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unhandled Expression Type: {0} 的本地化字符串。
        /// </summary>
        internal static string UnhandledExpressionType {
            get {
                return ResourceManager.GetString("UnhandledExpressionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Member &apos;{0}&apos; on node type &apos;{1}&apos; does not have a known translation to SQL. 的本地化字符串。
        /// </summary>
        internal static string UnhandledMemberAccess {
            get {
                return ResourceManager.GetString("UnhandledMemberAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SQL Server does not handle comparison of NText, Text, Xml, or Image data types. 的本地化字符串。
        /// </summary>
        internal static string UnhandledStringTypeComparison {
            get {
                return ResourceManager.GetString("UnhandledStringTypeComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Types in Union or Concat have members assigned in different order. 的本地化字符串。
        /// </summary>
        internal static string UnionDifferentMemberOrder {
            get {
                return ResourceManager.GetString("UnionDifferentMemberOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Types in Union or Concat have different members assigned. 的本地化字符串。
        /// </summary>
        internal static string UnionDifferentMembers {
            get {
                return ResourceManager.GetString("UnionDifferentMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Types in Union or Concat are constructed incompatibly. 的本地化字符串。
        /// </summary>
        internal static string UnionIncompatibleConstruction {
            get {
                return ResourceManager.GetString("UnionIncompatibleConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sources of type (GetType() or typeof) are incompatible for Union-like operation. 的本地化字符串。
        /// </summary>
        internal static string UnionOfIncompatibleDynamicTypes {
            get {
                return ResourceManager.GetString("UnionOfIncompatibleDynamicTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Types in Union or Concat cannot be constructed with hierarchy. 的本地化字符串。
        /// </summary>
        internal static string UnionWithHierarchy {
            get {
                return ResourceManager.GetString("UnionWithHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data member &apos;{0}&apos; of type &apos;{1}&apos; is not part of the mapping for type &apos;{2}&apos;. Is the member above the root of an inheritance hierarchy? 的本地化字符串。
        /// </summary>
        internal static string UnmappedDataMember {
            get {
                return ResourceManager.GetString("UnmappedDataMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized expression node: {0} 的本地化字符串。
        /// </summary>
        internal static string UnrecognizedExpressionNode {
            get {
                return ResourceManager.GetString("UnrecognizedExpressionNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; is not a valid provider mode. 的本地化字符串。
        /// </summary>
        internal static string UnrecognizedProviderMode {
            get {
                return ResourceManager.GetString("UnrecognizedProviderMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsafe string conversion from {0} to {1} may lead to implicit truncation.  Try reshaping the string explicitly with a Substring operation. 的本地化字符串。
        /// </summary>
        internal static string UnsafeStringConversion {
            get {
                return ResourceManager.GetString("UnsafeStringConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DateTime constructor form is not supported. 的本地化字符串。
        /// </summary>
        internal static string UnsupportedDateTimeConstructorForm {
            get {
                return ResourceManager.GetString("UnsupportedDateTimeConstructorForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DateTimeOffset constructor form is not supported. 的本地化字符串。
        /// </summary>
        internal static string UnsupportedDateTimeOffsetConstructorForm {
            get {
                return ResourceManager.GetString("UnsupportedDateTimeOffsetConstructorForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The node type &apos;{0}&apos; is not supported. 的本地化字符串。
        /// </summary>
        internal static string UnsupportedNodeType {
            get {
                return ResourceManager.GetString("UnsupportedNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 String constructor form is not supported. 的本地化字符串。
        /// </summary>
        internal static string UnsupportedStringConstructorForm {
            get {
                return ResourceManager.GetString("UnsupportedStringConstructorForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TimeSpan constructor form is not supported. 的本地化字符串。
        /// </summary>
        internal static string UnsupportedTimeSpanConstructorForm {
            get {
                return ResourceManager.GetString("UnsupportedTimeSpanConstructorForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constructor for server type &apos;{0}&apos; is not supported. 的本地化字符串。
        /// </summary>
        internal static string UnsupportedTypeConstructorForm {
            get {
                return ResourceManager.GetString("UnsupportedTypeConstructorForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The item of an update must be a constant value expression. 的本地化字符串。
        /// </summary>
        internal static string UpdateItemMustBeConstant {
            get {
                return ResourceManager.GetString("UpdateItemMustBeConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value has no literal in SQL: {0} 的本地化字符串。
        /// </summary>
        internal static string ValueHasNoLiteralInSql {
            get {
                return ResourceManager.GetString("ValueHasNoLiteralInSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot translate multiple character ranges in the pattern argument. 的本地化字符串。
        /// </summary>
        internal static string VbLikeDoesNotSupportMultipleCharacterRanges {
            get {
                return ResourceManager.GetString("VbLikeDoesNotSupportMultipleCharacterRanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pattern contains unclosed bracket. 的本地化字符串。
        /// </summary>
        internal static string VbLikeUnclosedBracket {
            get {
                return ResourceManager.GetString("VbLikeUnclosedBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The query contains references to items defined on a different data context. 的本地化字符串。
        /// </summary>
        internal static string WrongDataContext {
            get {
                return ResourceManager.GetString("WrongDataContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrong number of values in &apos;{0}&apos;. Expected {1}. Actually {2}. 的本地化字符串。
        /// </summary>
        internal static string WrongNumberOfValuesInCollectionArgument {
            get {
                return ResourceManager.GetString("WrongNumberOfValuesInCollectionArgument", resourceCulture);
            }
        }
    }
}
