//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALinq.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ALinq_Mapping {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ALinq_Mapping() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALinq.Resources.ALinq.Mapping", typeof(ALinq_Mapping).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Abstract class &apos;{0}&apos; should not be assigned an inheritance discriminator key. 的本地化字符串。
        /// </summary>
        internal static string AbstractClassAssignInheritanceDiscriminator {
            get {
                return ResourceManager.GetString("AbstractClassAssignInheritanceDiscriminator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mapping Problem: Bad function type in mapping for method &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string BadFunctionTypeInMethodMapping {
            get {
                return ResourceManager.GetString("BadFunctionTypeInMethodMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find key member &apos;{0}&apos; of key &apos;{1}&apos; on type &apos;{2}&apos;. The key may be wrong or the field or property on &apos;{2}&apos; has changed names. 的本地化字符串。
        /// </summary>
        internal static string BadKeyMember {
            get {
                return ResourceManager.GetString("BadKeyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bad Storage property: &apos;{0}&apos; on member &apos;{1}.{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string BadStorageProperty {
            get {
                return ResourceManager.GetString("BadStorageProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interface &apos;{0}&apos; is inaccessible. 的本地化字符串。
        /// </summary>
        internal static string CannotAccessInterface {
            get {
                return ResourceManager.GetString("CannotAccessInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mapping Problem: Cannot get inheritance default from class not mapped into an inheritance hierarchy. 的本地化字符串。
        /// </summary>
        internal static string CannotGetInheritanceDefaultFromNonInheritanceClass {
            get {
                return ResourceManager.GetString("CannotGetInheritanceDefaultFromNonInheritanceClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not create PropertyAccessor&lt;{0},{1}&gt; to {2}. 的本地化字符串。
        /// </summary>
        internal static string CouldNotCreateAccessorToProperty {
            get {
                return ResourceManager.GetString("CouldNotCreateAccessorToProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mapping Problem: Could not find element type in model for &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string CouldNotFindElementTypeInModel {
            get {
                return ResourceManager.GetString("CouldNotFindElementTypeInModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mapping Problem: Cannot find mapping for data context type &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string CouldNotFindMappingForDataContextType {
            get {
                return ResourceManager.GetString("CouldNotFindMappingForDataContextType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mapping Problem: Could not find required attribute &apos;{0}&apos;: {1}. 的本地化字符串。
        /// </summary>
        internal static string CouldNotFindRequiredAttribute {
            get {
                return ResourceManager.GetString("CouldNotFindRequiredAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mapping Problem: Cannot find runtime type for type mapping &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string CouldNotFindRuntimeTypeForMapping {
            get {
                return ResourceManager.GetString("CouldNotFindRuntimeTypeForMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mapping Problem: Cannot find type &apos;{0}&apos; from mapping. 的本地化字符串。
        /// </summary>
        internal static string CouldNotFindTypeFromMapping {
            get {
                return ResourceManager.GetString("CouldNotFindTypeFromMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database node not found.  Is the mapping namespace ({0}) correctly specified? 的本地化字符串。
        /// </summary>
        internal static string DatabaseNodeNotFound {
            get {
                return ResourceManager.GetString("DatabaseNodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The data context type &apos;{0}&apos; is mapped more than once. 的本地化字符串。
        /// </summary>
        internal static string DataContextTypeMappedMoreThanOnce {
            get {
                return ResourceManager.GetString("DataContextTypeMappedMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discriminator &apos;{0}.{1}&apos; may not be type &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string DiscriminatorClrTypeNotSupported {
            get {
                return ResourceManager.GetString("DiscriminatorClrTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The EntityRef is already loaded and the source cannot be changed. 的本地化字符串。
        /// </summary>
        internal static string EntityRefAlreadyLoaded {
            get {
                return ResourceManager.GetString("EntityRefAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Element &apos;{0}&apos; must be empty, but contains a node of type {1} named &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ExpectedEmptyElement {
            get {
                return ResourceManager.GetString("ExpectedEmptyElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid type mapping for Identity member &apos;{0}.{1}&apos;.  Type &apos;{2}&apos; is not supported for identity members. 的本地化字符串。
        /// </summary>
        internal static string IdentityClrTypeNotSupported {
            get {
                return ResourceManager.GetString("IdentityClrTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incorrect AutoSync specification for member &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string IncorrectAutoSyncSpecification {
            get {
                return ResourceManager.GetString("IncorrectAutoSyncSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mapping Problem: Incorrect number of parameters mapped for method &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string IncorrectNumberOfParametersMappedForMethod {
            get {
                return ResourceManager.GetString("IncorrectNumberOfParametersMappedForMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inheritance code value may not be null. 的本地化字符串。
        /// </summary>
        internal static string InheritanceCodeMayNotBeNull {
            get {
                return ResourceManager.GetString("InheritanceCodeMayNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The inheritance code &apos;{0}&apos; is used for multiple types. 的本地化字符串。
        /// </summary>
        internal static string InheritanceCodeUsedForMultipleTypes {
            get {
                return ResourceManager.GetString("InheritanceCodeUsedForMultipleTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The inheritance hierarchy rooted at &apos;{0}&apos; does not define a default. 的本地化字符串。
        /// </summary>
        internal static string InheritanceHierarchyDoesNotDefineDefault {
            get {
                return ResourceManager.GetString("InheritanceHierarchyDoesNotDefineDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The inheritance subtype &apos;{0}&apos; is also declared as a root type. 的本地化字符串。
        /// </summary>
        internal static string InheritanceSubTypeIsAlsoRoot {
            get {
                return ResourceManager.GetString("InheritanceSubTypeIsAlsoRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inheritance type &apos;{0}&apos; does not derive from inheritance root type &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string InheritanceTypeDoesNotDeriveFromRoot {
            get {
                return ResourceManager.GetString("InheritanceTypeDoesNotDeriveFromRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The inheritance type &apos;{0}&apos; has multiple defaults. 的本地化字符串。
        /// </summary>
        internal static string InheritanceTypeHasMultipleDefaults {
            get {
                return ResourceManager.GetString("InheritanceTypeHasMultipleDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The inherited type &apos;{0}&apos; cannot have multiple discriminator key values. 的本地化字符串。
        /// </summary>
        internal static string InheritanceTypeHasMultipleDiscriminators {
            get {
                return ResourceManager.GetString("InheritanceTypeHasMultipleDiscriminators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid DeleteOnNull specification for member &apos;{0}&apos;. DeleteOnNull can only be true for singleton association members mapped to non-nullable foreign key columns. 的本地化字符串。
        /// </summary>
        internal static string InvalidDeleteOnNullSpecification {
            get {
                return ResourceManager.GetString("InvalidDeleteOnNullSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not create FieldAccessor&lt;{0},{1}&gt; from FieldInfo &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string InvalidFieldInfo {
            get {
                return ResourceManager.GetString("InvalidFieldInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid use of generic method &apos;{0}&apos; as mapped function. 的本地化字符串。
        /// </summary>
        internal static string InvalidUseOfGenericMethodAsMappedFunction {
            get {
                return ResourceManager.GetString("InvalidUseOfGenericMethodAsMappedFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Link is already loaded and the source cannot be changed. 的本地化字符串。
        /// </summary>
        internal static string LinkAlreadyLoaded {
            get {
                return ResourceManager.GetString("LinkAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The column or association &apos;{0}&apos; in the mapping had no corresponding member in type &apos;{1}&apos;. Mapping members from above root type is not supported. 的本地化字符串。
        /// </summary>
        internal static string MappedMemberHadNoCorrespondingMemberInType {
            get {
                return ResourceManager.GetString("MappedMemberHadNoCorrespondingMemberInType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mapping Problem: Mapping for table &apos;{0}&apos; is not defined. 的本地化字符串。
        /// </summary>
        internal static string MappingForTableUndefined {
            get {
                return ResourceManager.GetString("MappingForTableUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The mapping of interface member {0}.{1} is not supported. 的本地化字符串。
        /// </summary>
        internal static string MappingOfInterfacesMemberIsNotSupported {
            get {
                return ResourceManager.GetString("MappingOfInterfacesMemberIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The member &apos;{0}&apos; is mapped more than once. 的本地化字符串。
        /// </summary>
        internal static string MemberMappedMoreThanOnce {
            get {
                return ResourceManager.GetString("MemberMappedMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method &apos;{0}&apos; cannot be found. 的本地化字符串。
        /// </summary>
        internal static string MethodCannotBeFound {
            get {
                return ResourceManager.GetString("MethodCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of ThisKey columns is different from the number of OtherKey columns for the association property &apos;{0}&apos; in the type &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string MismatchedThisKeyOtherKey {
            get {
                return ResourceManager.GetString("MismatchedThisKeyOtherKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified type &apos;{0}&apos; must be interface. 的本地化字符串。
        /// </summary>
        internal static string MustBeInterface {
            get {
                return ResourceManager.GetString("MustBeInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The inheritance type &apos;{0}&apos; does not declare a discriminator column. 的本地化字符串。
        /// </summary>
        internal static string NoDiscriminatorFound {
            get {
                return ResourceManager.GetString("NoDiscriminatorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The inheritance type &apos;{0}&apos; has a discriminator but is not part of a mapped inheritance hierarchy. 的本地化字符串。
        /// </summary>
        internal static string NonInheritanceClassHasDiscriminator {
            get {
                return ResourceManager.GetString("NonInheritanceClassHasDiscriminator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No result types declared for function &apos;{0}&apos; that returns IMultipleResults. 的本地化字符串。
        /// </summary>
        internal static string NoResultTypesDeclaredForFunction {
            get {
                return ResourceManager.GetString("NoResultTypesDeclaredForFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ALinq 的本地化字符串。
        /// </summary>
        internal static string OwningTeam {
            get {
                return ResourceManager.GetString("OwningTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The subtype &apos;{0}&apos; cannot contain the primary key member &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string PrimaryKeyInSubTypeNotSupported {
            get {
                return ResourceManager.GetString("PrimaryKeyInSubTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specified provider type &apos;{0}&apos; not found. 的本地化字符串。
        /// </summary>
        internal static string ProviderTypeNotFound {
            get {
                return ResourceManager.GetString("ProviderTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More than one result type declared for function &apos;{0}&apos; that does not return IMultipleResults. 的本地化字符串。
        /// </summary>
        internal static string TooManyResultTypesDeclaredForFunction {
            get {
                return ResourceManager.GetString("TooManyResultTypesDeclaredForFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Members &apos;{0}&apos; and &apos;{1}&apos; both marked as inheritance discriminator. 的本地化字符串。
        /// </summary>
        internal static string TwoMembersMarkedAsInheritanceDiscriminator {
            get {
                return ResourceManager.GetString("TwoMembersMarkedAsInheritanceDiscriminator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Members &apos;{0}&apos; and &apos;{1}&apos; both marked as IsPrimaryKey and IsDbGenerated. 的本地化字符串。
        /// </summary>
        internal static string TwoMembersMarkedAsPrimaryKeyAndDBGenerated {
            get {
                return ResourceManager.GetString("TwoMembersMarkedAsPrimaryKeyAndDBGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Members &apos;{0}&apos; and &apos;{1}&apos; both marked as row version. 的本地化字符串。
        /// </summary>
        internal static string TwoMembersMarkedAsRowVersion {
            get {
                return ResourceManager.GetString("TwoMembersMarkedAsRowVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; does not contains member &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string TypeNotContainsMember {
            get {
                return ResourceManager.GetString("TypeNotContainsMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to assign value to read only property &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string UnableToAssignValueToReadonlyProperty {
            get {
                return ResourceManager.GetString("UnableToAssignValueToReadonlyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mapping Problem: Unable to resolve root for type &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string UnableToResolveRootForType {
            get {
                return ResourceManager.GetString("UnableToResolveRootForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected element &apos;{0}&apos;, but found &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedElement {
            get {
                return ResourceManager.GetString("UnexpectedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected null &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedNull {
            get {
                return ResourceManager.GetString("UnexpectedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unhandled deferred storage type: {0}. 的本地化字符串。
        /// </summary>
        internal static string UnhandledDeferredStorageType {
            get {
                return ResourceManager.GetString("UnhandledDeferredStorageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Class member {0}.{1} is unmapped. 的本地化字符串。
        /// </summary>
        internal static string UnmappedClassMember {
            get {
                return ResourceManager.GetString("UnmappedClassMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized attribute &apos;{0}&apos; in mapping file. 的本地化字符串。
        /// </summary>
        internal static string UnrecognizedAttribute {
            get {
                return ResourceManager.GetString("UnrecognizedAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized element &apos;{0}&apos; in mapping file. 的本地化字符串。
        /// </summary>
        internal static string UnrecognizedElement {
            get {
                return ResourceManager.GetString("UnrecognizedElement", resourceCulture);
            }
        }
    }
}
