//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALinq.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALinq.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly name is not match, expected &apos;{0}&apos;, acutal &apos;{1}&apos;..
        /// </summary>
        internal static string AssemblyNameNotMatch {
            get {
                return ResourceManager.GetString("AssemblyNameNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get a assembly name from the license file..
        /// </summary>
        internal static string CannotGetAssemblyName {
            get {
                return ResourceManager.GetString("CannotGetAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get a license key from the license file..
        /// </summary>
        internal static string CannotGetLicenseKey {
            get {
                return ResourceManager.GetString("CannotGetLicenseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get a user name from the license file..
        /// </summary>
        internal static string CannotGetUserName {
            get {
                return ResourceManager.GetString("CannotGetUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license file(ALinq.lic) format is error, please regenerate the license file..
        /// </summary>
        internal static string LicenseFileErrorFormat {
            get {
                return ResourceManager.GetString("LicenseFileErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software is expired..
        /// </summary>
        internal static string SoftwareExpired {
            get {
                return ResourceManager.GetString("SoftwareExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate the license for &apos;{0}&apos; fail..
        /// </summary>
        internal static string ValidateLicenseFail {
            get {
                return ResourceManager.GetString("ValidateLicenseFail", resourceCulture);
            }
        }
    }
}
